package com.ganatragmail.sagar.fightbetter;

import android.annotation.TargetApi;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.support.v4.app.ListFragment;
import android.support.v7.app.ActionBarActivity;
import android.view.ActionMode;
import android.view.ContextMenu;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AbsListView;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

/**
    CrimeListFragment - Contains Code for
    1. Setting ListAdapter with ArrayList of Crime Objects
    2. Inflating CrimeListFragment view
    3. ActionListeners for TitleBar/ActionBar, SubtitleBar, ListItemClick
    4. ActionListener for ListItemClick which opens CrimeFragment using Explicit Intents
    5. Code for inflating Context Menu(Floating as well as ActionMode) on long-click of list item as well as listeners for context objects
    6. Code for inflating handling Options Menu (Add crime)
 */



public class CrimeListFragment extends ListFragment {

    //REQUEST_CODE sent to CrimeFragment along with Intent when StartActivityForResult is called
    private static int REQUEST_CRIME = 1;

    private ArrayList<Crime> mCrimes;

    //Used to toggle between showing and hiding subtitle in the ActionBar


    @Override
    public void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setHasOptionsMenu(true);

        //Retains fragment after death of activity on screen - orientation change
        setRetainInstance(true);

              //Access ArrayList of Crimes using SingletonCrimeAccessor and sets custom ArrayList adapter (created further below) for display
        mCrimes = SingletonCrimeAccessor.get(getActivity()).getCrimes();
        CrimeAdapter adapter = new CrimeAdapter(mCrimes);
        setListAdapter(adapter);


    }



    //Create Custom CrimeAdapter to be able to have custom list item view-
    // Override the method getView from ArrayAdapter class.
    private class CrimeAdapter extends ArrayAdapter<Crime> {

        public CrimeAdapter(ArrayList<Crime> crimes){
            super(getActivity(), 0, crimes);
        }

        @Override
        public View getView (int position, View convertView, ViewGroup parent){
            if (convertView == null){
                convertView = getActivity().getLayoutInflater()
                        .inflate(R.layout.list_item_crime, null);

            }

            //Configure the View item
            Crime c = getItem(position);

            TextView titleTextView = (TextView)convertView.findViewById(R.id.crime_list_item_titleTextView);
            titleTextView.setText(c.getTitle());

            TextView dateView = (TextView)convertView.findViewById(R.id.crime_item_dateTextView);
            dateView.setText(c.getDate().toString());


            TextView suspectTextView = (TextView)convertView.findViewById(R.id.crime_item_suspectTextView);
            suspectTextView.setText(c.getSuspect());


            return convertView;
        }
    }




    @TargetApi(11)
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup parent, Bundle savedInstanceState) {
        View v = super.onCreateView(inflater, parent, savedInstanceState);

        //Subtitle is available for phones with HoneyComb or later only
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            ((ActionBarActivity) getActivity()).getSupportActionBar().setSubtitle(R.string.subtitleCrimeListFragment);
        }else {

            getActivity().setTitle(R.string.subtitleCrimeListFragment);
        }

        //Use listView-id generated by Android. This id is used to get context menu for long clicked items on ListView
        ListView listView = (ListView)v.findViewById(android.R.id.list);


        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB ){

            registerForContextMenu(listView); //Register Floating ContextMenu on Listview

        }
        else {
            //For API>HoneyComb - Register Action Mode Contextual Menu with ability to select multiple list items
            // and show context menu on ActionBar
            listView.setChoiceMode(listView.CHOICE_MODE_MULTIPLE_MODAL);
            //Set ActionListener for ListView long click
            listView.setMultiChoiceModeListener(new AbsListView.MultiChoiceModeListener() {
                @Override
                public void onItemCheckedStateChanged(ActionMode mode, int position, long id, boolean checked) {

                }

                @Override
                public boolean onCreateActionMode(ActionMode mode, Menu menu) {
                    //Inflate Context menu
                    MenuInflater inflater = mode.getMenuInflater();
                    inflater.inflate(R.menu.crime_list_item_context, menu);
                    return true;

                }

                @Override
                public boolean onPrepareActionMode(ActionMode mode, Menu menu) {
                    return false;
                }

                @Override
                public boolean onActionItemClicked(ActionMode mode, MenuItem item) {

                    //Handle actions based on Context menu item clicked
                    switch (item.getItemId()){
                        case R.id.menu_item_delete_crime:
                            CrimeAdapter adapter = (CrimeAdapter)getListAdapter();
                            SingletonCrimeAccessor singletonCrimeAccessor = com.ganatragmail.sagar.fightbetter.SingletonCrimeAccessor.get(getActivity());
                            for (int i=adapter.getCount()-1; i >=0; i--) {
                                if(getListView().isItemChecked(i)){
                                    singletonCrimeAccessor.deleteCrime(adapter.getItem(i));
                                }

                            }
                            mode.finish();
                            adapter.notifyDataSetChanged();
                            return true;
                        default:
                            return false;

                    }
                }

                @Override
                public void onDestroyActionMode(ActionMode mode) {

                }
            });
        }

        return v;
    }



    //ActionListener for list item clicked on ListView. Opens CrimeFragment with intent(intent is directed to parent activity) and REQUEST_CODE.
    @Override
    public void onListItemClick(ListView l, View v, int position,long id){
        Crime c = ((CrimeAdapter)getListAdapter()).getItem(position);
        //Log.d(TAG, c.getTitle() + " was clicked");

        //Start P
        // Pager Activity. Add the UUID of the crime item selected along with the Intent
        Intent intent = new Intent(getActivity(),PagerActivity.class);
        intent.putExtra(CrimeFragment.EXTRA_CRIME_ID, c.getId());
        startActivityForResult(intent, REQUEST_CRIME);

    }

    //Inflates floating context menu
    @Override
    public void onCreateContextMenu(ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo){
        getActivity().getMenuInflater().inflate(R.menu.crime_list_item_context, menu);
    }

    // OnContextItem Selected - Handles events based on which menu item is selected in the floating context menu
    @Override
    public boolean onContextItemSelected(MenuItem item){
        AdapterView.AdapterContextMenuInfo info = (AdapterView.AdapterContextMenuInfo)item.getMenuInfo();
        int position = info.position;
        CrimeAdapter adapter = (CrimeAdapter)getListAdapter();
        Crime crime = adapter.getItem(position);

        switch (item.getItemId()) {

            case R.id.menu_item_delete_crime:
                SingletonCrimeAccessor.get(getActivity()).deleteCrime(crime);
                adapter.notifyDataSetChanged();
                return true;

            default:
                return super.onContextItemSelected(item);


        }

    }




    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater){
        super.onCreateOptionsMenu(menu, inflater);
        inflater.inflate(R.menu.fragment_crime_list, menu);

    }

    @TargetApi(11)
    @Override
    public boolean onOptionsItemSelected(MenuItem item){
        switch(item.getItemId()){

            case R.id.menu_item_crime:
                Crime crime = new Crime();
                SingletonCrimeAccessor.get(getActivity()).addCrime(crime);
                Intent i = new Intent(getActivity(),PagerActivity.class);
                i.putExtra(CrimeFragment.EXTRA_CRIME_ID,crime.getId());
                startActivityForResult(i, 0);
                return true;

            default:
                return super.onOptionsItemSelected(item);
        }

    }

    @Override
    public void onResume(){
        super.onResume();
        ((CrimeAdapter)getListAdapter()).notifyDataSetChanged();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data){
        if (requestCode == REQUEST_CRIME){
            ((CrimeAdapter)getListAdapter()).notifyDataSetChanged();
        }

    }

}
